name: 'ffmpeg benchmark'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test-conversion
        run: |
         sudo apt update && sudo apt install -y ffmpeg
         wget https://cobras.hockey/Goals.mp4
         ffmpeg -i Goals.mp4 test.mp4
     
